### ISSUE TITLE
Implement GitHub Actions for versioning, auto-publishing to Nuget.org

### ISSUE THREAD

**Issue by cpdohert** [codemonarchs/OpenAISharp#4]
Should use GitVersion to automatically bump the versions on merge to [main]

@tuneis Do you want OpenAISharp to act as a meta-package that pulls in all the specific packages?  Or do all the specific packages absolutely require the parent OpenAiSharp library?

**Comment by cpdohert** [comment]
The current workflow is a one job matrix.  We only want to tag and publish once, so we need to create a multi-job pipeline that runs the matrix builds,

**Comment by codemonarchs** [comment]
> Should use GitVersion to automatically bump the versions on merge to [main]
> 
> @tuneis Do you want OpenAISharp to act as a meta-package that pulls in all the specific packages? Or do all the specific packages absolutely require the parent OpenAiSharp library?

As a Meta package that pulls them all in. 
All of the packages do not require the OpenAISharp package and can be consumed individually by pulling in minimum of 2:
- OpenAISharp.Client and OpenAISharp.PackageName (Completion for example)

**Comment by codemonarchs** [comment]
@cpdohert For versioning, I think it's ok that we version them all together and deploy them all to NuGet with the bump even if there are only code changes in one lib.

**Comment by cpdohert** [comment]
Completed.
