### ISSUE TITLE
Add NuGet.org API token as a Repository Secret

### ISSUE THREAD

**Issue by cpdohert** [codemonarchs/OpenAISharp#46]
Per https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository

please add the CodeMonarchs NuGet.org API token as a Repository Secret named `NUGET_ORG_API_TOKEN`

I can't do it because this is restricted to the repo owner.

**Comment by codemonarchs** [comment]
@cpdohert Added.
